sudo: false
language: python
matrix:
  include:
    - python: "3.6"
      env: LTD_SKIP_UPLOAD=false
install:
  - pip install -r requirements.txt
script:
  - cd docs && make html && cd ../
  - ltd upload --product "felis" --travis --dir docs/_build/html
env:
  global:
    - LTD_SKIP_UPLOAD=true  # disable doc uploads by default
    # AWS and LTD Keeper credentials as encrypted secrets
    - secure: "KRNrAqWEYpOOOGa3Gp2w7EV2lriTyz8KurX5oq0SahKrmTJ7Cj4JpBEbu+fq7q2f549ZOhCuhioUp2hQWtXmQ4O3IeP2seSDsIQrKSFhIgOl0Zuwe+0G1l7rtF6ZkEgOlZHkYv/kQkzCMzd8nyGc9/JvMHR3gkazO6kOtBKCjOh3hGjbq7l+ACn8viMAy3XIx4p7t2Q1dfEg4s+AdhNMxQPgc9kdfqfC/zfFvBZqKZoAFjrJ3im4ifuvF1rWY0m+pfZSi2G1HjXSXdJOFj3nlTyD3vB3l1YmZ/XWqLw4toMhDDqbRuy8d5+5NIAb5ae8C6QMRf96k9Hf1KN3mnHtuNIA2sAyJdlhY02ttwU4HmY0zXlDemABb7MvXJEcX37oa74RQMpBiMHAYnNS/xKO5zZuZSLsUa26CkNbXkTRWdpxuBubb0fivpnHc/ZQ4nLCJVSNNqO+xOBHNkJ9Fygqp1eW2l2eB2ODJPYu+VJ9p09KR4L2ogFpm7DpmuF3b1HDlBXTbHhZHIEQCqzGef/6aULFXsG+uhulM65jmxBFM8q507QbIHYX3wj4+E25DZKfe8IjN+BuH+QWKcao+gFSvNc/NEnXW6MztJfepW7QDxA+C9+a++OD7djNm5PjNtatv4PjLywkA7WLiezp3YHdszjQToOm3G5nb/4OizH3mzM="
    - secure: "axsJljwSogqONDNoUYni3ljD7FqGcrDyxj4UcDYvqXtx9WQ/M1V3adMDpRUO4JQS9OmYxRjkvhK/8CSWEiBJKeMlDJnZoUgPnqNxgTnt6Sh7R8LyEY4NHOe0/uNXVzPjjhaj28MIZp0WRW9y5qTRTVVcRZURW/pJ6rc93qWwvnbPkSz8RFP+1VPYQFNNaEEjZo1ZkEVDhxuKfOrp+Ma74ceAV6OYT9aFOYpqUHWV2VOr5B0wxpsdvS71Ay7bI5xxYW0Q5L+106E67zCgMnM20I55EpLoJs6mzh4JWz53asEa5SPZFtkUwUgBBuuv+QxvW6Vmly6OCOMepWPf/P8uNYjTtNvU8mn9u+UKcVwniCddA9EhIygGGbsTtCFIGr9Q3gOFJ1Fw9gmCj6422mojoAD5Q4SQzf1UIUUQdbzdWWSlIb8Z48NVka12R6xHvCawm7m75SmLsv/nQIMFDNA3mOKJduEiOB7hrcc3ZjtRrUOCjtGmBUytwaGjZYA5GaMwGtduVkPGAWDVei2g5FOGbIwvLRBW1OeJcdgHYwN52xmXKnUka4JsrVIKAWvqtUb6htBep9aLXC74mP7t62yl0bzQ4oOXhpJWZF5KRPYIXfwL9n20154jd9IuJgVeSuZRZ4AUeR4Mal5CG9EdwQnotqWkbSmXmtEDXxmO7mN5wes="
